env:
  - Project=github.com/pubgo/protoc-gen-openapi
builds:
  - main: ./main.go
    binary: protoc-gen-openapi
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - "-X '{{ .ModulePath }}/version.version={{ .Version }}'"
      - "-X '{{ .ModulePath }}/version.commit={{ .Commit }}'"
      - "-X '{{ .ModulePath }}/version.date={{ .CommitTimestamp }}'"
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "{{ .Tag }}_checksums.txt"
report_sizes: true
